version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: football_games
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: